# ========== SUPER-RESOLUTION CONFIG ==========

paths:
  raw_data: "data/raw"               # dossier contenant HR/ et LR/
  output_root: "data/preprocessed"   # dossier final après split + patching
  checkpoints: "src/models/checkpoints" 

dataset:
  scale: 4
  grid: 23
  hr_patch: 128          # HR size
  lr_patch: 32           # LR size 
  train_ratio: 0.80
  val_ratio: 0.10
  test_ratio: 0.10

# optionnel : seed pour reproductibilité
random_seed: 42


training:
  batch_size: 64
  num_workers: 8
  epochs: 70
  lr: 0.0001
  weight_decay: 0.0
  scheduler_step_size: 20   # StepLR: tous les 20 epochs
  scheduler_gamma: 0.5      # LR = LR * 0.5
  use_augmentation: True    # data augmentation sur le train




model:
  best_SRCNN_path: "src/models/checkpoints/SRCNN/best_srcnn.pth"  
  last_SRCNN_path: "src/models/checkpoints/SRCNN/last_srcnn.pth"

  best_EDSR_path: "src/models/checkpoints/EDSR/best_EDSR.pth"
  last_EDSR_path: "src/models/checkpoints/EDSR/last_EDSR.pth"

  best_EDSR_v1_path: "src/models/checkpoints/EDSR_v1/best_EDSR_v1.pth"

  best_EDSR_PRO_path: "src/models/checkpoints/EDSR_PRO/best_EDSR_PRO.pth"

  best_SRESNET_path: "src/models/checkpoints/SRESNET/best_SRESNET.pth"
  last_SRESNET_path: "src/models/checkpoints/SRESNET/last_SRESNET.pth"
  


history:
  SRCNN_history_path: "src/models/checkpoints/SRCNN/srcnn_training_history.json" 


  EDSR_history_path : "src/models/checkpoints/EDSR/edsr_training_history.json"
  
  EDSR_v1_history_path : "src/models/checkpoints/EDSR_v1/edsr_v1_training_history.json"

  EDSR_PRO_history_path : "src/models/checkpoints/EDSR_PRO/edsr_PRO_training_history.json"

  SRESNET_history_path : "src/models/checkpoints/SRESNET/srresnet.json"