# ========== SUPER-RESOLUTION CONFIG ==========

paths:
  raw_data: "data/raw"               # dossier contenant HR/ et LR/
  output_root: "data/preprocessed"   # dossier final après split + patching
  checkpoints: "src/models/checkpoints" 

dataset:
  scale: 4
  grid: 15
  hr_patch: 192          # taille patch HR
  lr_patch: 48           # sera recalculé automatiquement si tu veux
  train_ratio: 0.80
  val_ratio: 0.10
  test_ratio: 0.10

# optionnel : seed pour reproductibilité
random_seed: 42


training:
  batch_size: 64
  num_workers: 8
  epochs: 10
  lr: 0.0001
  weight_decay: 0.0
  scheduler_step_size: 20   # StepLR: tous les 20 epochs
  scheduler_gamma: 0.5      # LR = LR * 0.5
  use_augmentation: true    # data augmentation sur le train




model:
  best_SRCNN_path: "src/models/checkpoints/best_srcnn.pth"  
  best_EDSR_path: "src/models/checkpoints/best_EDSR.pth"
  best_SRESNET_path: "src/models/checkpoints/best_SRESNET.pth"


history:
  SRESNET_history : "src/models/srresnet_history.json"